### ISSUE TITLE
Language option not url encoded. 

### ISSUE THREAD

**Issue by christopher-eddy-state-ca-gov** [GSA/code-gov-api-client#16]
**Describe the bug**
Language options not being url encoded. This causes problems for c# and c++ languages.

**To Reproduce**
1. Go to Browse-Projects or Search Page
2. Click language filter box for "C#" and and "C++"
3.  Notice that incorrect results return because api client strips off symbols in call to ElasticSearch

**Expected behavior**
The proper search return for languages, including symbols.

**Screenshots**
![image](https://user-images.githubusercontent.com/36239148/53365940-48be0100-38f7-11e9-82ef-7a77350b66fa.png)

**Desktop (please complete the following information):**
 - OS: *
 - Browser chrome/others
 - Version Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by hendersonanalytics** [comment]
This is causing issues on the front end of code.gov as well:

https://github.com/GSA/code-gov-front-end/issues/161
https://github.com/GSA/code-gov-front-end/issues/151

@saracope If we fix this issue with `code-gov-api-client` it will solve the two issues referenced above. 3 birds with 1 stone.
