### ISSUE TITLE
Add contact info to README.md

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-api-client#21]
Add a section the README.md file with the heading **Questions?** section and add the following info:

Twitter: [@CodeDotGov](https://twitter.com/CodeDotGov)
Email: code@gsa.gov
LinkedIn: [code-gov](https://www.linkedin.com/company/code-gov)
Join our #opensource-public Slack channel: https://chat.18f.gov/

**Comment by k-cogswell** [comment]
@saracope I can take this on

**Comment by saracope** [comment]
Please be sure the items listed actually link out to the source.
